name: Build website

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: website
    
    - name: Build website
      working-directory: website
      run: |
        mkdir tmp
        mkdir dist
        mkdir dist\tags
        mkdir dist\resources
        xcopy resources dist\resources /E
        php build.php
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
